### ISSUE TITLE
pep.py not working ?

### ISSUE THREAD

**Issue by ProKiller36016** [osuripple/ripple#167]
i can't run the pep.py

i install : 

- flask
- tornado
- pymysql
- psutil
- bcrypt

command : python3 /root/ripple/c.ppy.sh/pep.py 

and : 

Traceback (most recent call last):
  File "/root/ripple/c.ppy.sh/pep.py", line 15, in <module>
    import serverPackets
  File "/root/ripple/c.ppy.sh/serverPackets.py", line 4, in <module>
    import userHelper
  File "/root/ripple/c.ppy.sh/userHelper.py", line 1, in <module>
    import passwordHelper
  File "/root/ripple/c.ppy.sh/passwordHelper.py", line 3, in <module>
    import bcrypt
  File "/usr/local/lib/python3.5/dist-packages/bcrypt/__init__.py", line 24, in <module>
    from bcrypt import _bcrypt
ImportError: /usr/local/lib/python3.5/dist-packages/bcrypt/_bcrypt.so: undefined symbol: PyInt_FromLong
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 13, in <module>
    import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
  File "/root/ripple/c.ppy.sh/glob.py", line 3, in <module>
    import tokenList
  File "/root/ripple/c.ppy.sh/tokenList.py", line 1, in <module>
    import osuToken
  File "/root/ripple/c.ppy.sh/osuToken.py", line 4, in <module>
    import userHelper
  File "/root/ripple/c.ppy.sh/userHelper.py", line 1, in <module>
    import passwordHelper
  File "/root/ripple/c.ppy.sh/passwordHelper.py", line 3, in <module>
    import bcrypt
  File "/usr/local/lib/python3.5/dist-packages/bcrypt/__init__.py", line 24, in <module>
    from bcrypt import _bcrypt
ImportError: /usr/local/lib/python3.5/dist-packages/bcrypt/_bcrypt.so: undefined symbol: PyInt_FromLong

Original exception was:
Traceback (most recent call last):
  File "/root/ripple/c.ppy.sh/pep.py", line 15, in <module>
    import serverPackets
  File "/root/ripple/c.ppy.sh/serverPackets.py", line 4, in <module>
    import userHelper
  File "/root/ripple/c.ppy.sh/userHelper.py", line 1, in <module>
    import passwordHelper
  File "/root/ripple/c.ppy.sh/passwordHelper.py", line 3, in <module>
    import bcrypt
  File "/usr/local/lib/python3.5/dist-packages/bcrypt/__init__.py", line 24, in <module>
    from bcrypt import _bcrypt
ImportError: /usr/local/lib/python3.5/dist-packages/bcrypt/_bcrypt.so: undefined symbol: PyInt_FromLong

why ??

**Comment by avail** [comment]
As stated in the readmes, no support will be provided.

**Comment by ProKiller36016** [comment]
...
