### ISSUE TITLE
DB Connect Error

### ISSUE THREAD

**Issue by DevCocoa** [osuripple/ripple#168]
root@ip-172-31-17-40:/web/ripple# python3 c.ppy.sh/pep.py
           _                 __
          (_)              /  /
   ______ __ ____   ____  /  /____
  /  ___/  /  _  \/  _  \/  /  _  \
 /  /  /  /  /_) /  /_) /  /  ____/
/__/  /__/  .___/  .___/__/ \_____/
        /  /   /  /
       /__/   /__/

                          .. o  .
                         o.o o . o
                        oo...
                    __[]__
    nyo -->  _\:D/_/o_o_o_|__     u wot m8
             \""""""""""""""/
              \ . ..  .. . /
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Welcome to pep.py osu!bancho server v0.9
> Made by the Ripple team
> https://github.com/osuripple/ripple
> Press CTRL+C to exit

> Loading config file... Done
> Connecting to MySQL db... Error
[!] Error while connection to database. Please check your config.ini and run the server again
Traceback (most recent call last):
  File "c.ppy.sh/pep.py", line 274, in <module>
    glob.db = databaseHelper.db(glob.conf.config["db"]["host"], glob.conf.config["db"]["username"], glob.conf.config["db"]["password"], glob.conf.config["db"]["database"], int(glob.conf.config["db"]["pingtime"]))
  File "/web/ripple/c.ppy.sh/databaseHelper.py", line 24, in __init__
    self.connection = pymysql.connect(host=__host, user=__username, password=__password, db=__database, cursorclass=pymysql.cursors.DictCursor, autocommit=True)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 688, in __init__
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 906, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1114, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 981, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")

----

config.ini

[db]
host = localhost
username = root
password = password
database = ripple
pingtime = 600

[server]
server = tornado
host = 0.0.0.0
port = 5001
outputpackets = 0
outputrequesttime = 0
localizeusers = 0
timeouttime = 100
timeoutlooptime = 100

[flask]
threaded = 1
debug = 0
logger = 0

[ci]
key=changeme

**Comment by thehowl** [comment]
We can't help you out on anything except telling you that the reason for the error is clearly written in the stacktrace and you should probably learn how to read.
